services:
  - type: worker
    name: vermosa-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: vermosabot
      - key: GUILD_ID
        sync: false
      - key: VERIFIED_ROLE_ID
        sync: false
      - key: UNVERIFIED_ROLE_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: VERIFY_CHANNEL_ID
        sync: false
      - key: REFER_CHANNEL_ID
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: WEBSITE_URL
        sync: false
